version: "0.19.5.1.{build}"

skip_tags: true

environment:
  gettext: gettext-0.19.5.1
  mirrors: pacman-mirrors-20150722-2-any.pkg.tar.xz

cache:
  - '%gettext%.tar'
  - '%mirrors%'
  - C:\msys64\var\cache\pacman\pkg

init: # Simplify the PATH variable
  - "set PATH=\
      ;%SystemRoot%\\system32\
      ;%SystemRoot%\
      ;%SystemRoot%\\System32\\Wbem\
      ;C:\\Program Files\\7-Zip\
      ;C:\\Program Files (x86)\\Git\\cmd\
      ;C:\\Program Files\\AppVeyor\\BuildAgent\
      ;C:\\msys64\\usr\\bin\
    "

install:
  - .\msys2.bat

before_build: # Download content
  - "if not exist %gettext%.tar (
      appveyor DownloadFile
      http://ftp.gnu.org/pub/gnu/gettext/%gettext%.tar.xz &&
      7z x %gettext%.tar.xz > nul &&
      del %gettext%.tar.xz
    )"
  - 7z x %gettext%.tar > nul

build_script: # Build libintl with MSYS2
  - set MSYSTEM=MINGW64
  - "sh --login -c >nul 2>&1 \"exec 0</dev/null &&
      cd \"\"\"${gettext}\"\"\" &&
      ./configure &&
      make -C gettext-runtime/intl
    \""
  - set MSYSTEM=

after_build: # Package libintl-8.dll
  - copy %gettext%\gettext-runtime/intl/.libs/libintl-8.dll ..
  - sh --login -c "sha256sum libintl-8.dll > release.sha256"

artifacts:
  - path: libintl-8.dll
  - path: release.sha256

on_failure:
  - ps: "$blockRdp = $true; iex ((new-object net.webclient).DownloadString((\
      'https://raw.githubusercontent.com/appveyor/ci/master/scripts/\
      enable-rdp.ps1')))"

deploy:
  release: $(APPVEYOR_BUILD_VERSION)
  description: "[AppVeyor build](https://ci.appveyor.com/project/\
    $(APPVEYOR_REPO_NAME)/build/$(APPVEYOR_BUILD_VERSION))"
  provider: GitHub
  draft: true
  on: { appveyor_repo_tag: false }
  auth_token:
    secure: qty+OleXdcHipnzD0RGUfPbTpe5Q9WtPvIknOFhkaIzQ28ccEsMU1mKSKQ2lnLUn
